---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: network-console-prometheus
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-console-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-console-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: network-console-prometheus
subjects:
- kind: ServiceAccount
  name: network-console-prometheus
---
apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
    rule_files:
    scrape_configs:
      - job_name: 'consolemetrics'
        metrics_path: "/metrics/"
        scheme: "http"
        static_configs:
          - targets: ["network-console:9090"]
  web-config.yml: |
    # TLS configuration.
    #
    #tls_server_config:
    #  cert_file: /etc/tls/certs/tls.crt
    #  key_file: /etc/tls/certs/tls.key
    #
    #
    # Usernames and passwords required to connect to Prometheus.
    # Passwords are hashed with bcrypt: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt
    #basic_auth_users:
kind: ConfigMap
metadata:
  name: prometheus-server-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: network-console-prometheus
  name: network-console-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: network-console-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: network-console-prometheus
    spec:
      containers:
      - args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        - --web.config.file=/etc/prometheus/web-config.yml
        image: quay.io/prometheus/prometheus:v2.42.0
        imagePullPolicy: Always
        name: prometheus-server
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-config
        - mountPath: /prometheus
          name: prometheus-storage-volume
      serviceAccount: network-console-prometheus
      serviceAccountName: network-console-prometheus
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-server-config
        name: prometheus-config
      - emptyDir: {}
        name: prometheus-storage-volume
---
apiVersion: v1
kind: Service
metadata:
  name: network-console-prometheus
spec:
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: network-console-prometheus
  type: ClusterIP
